# -*- coding: utf-8 -*-
"""SU2_voxceleb1h.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnEU7kiGrcz4tNN-_cKlvCkl0mZaXEj4

#### Voxceleb1H datasat download
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!mkdir /content/voxceleb1h

from torchaudio.datasets import VoxCeleb1Verification

voxceleb1h_dataset = VoxCeleb1Verification(root='/content/voxceleb1h',
           meta_url = 'https://mm.kaist.ac.kr/datasets/voxceleb/meta/list_test_hard.txt',
                            download=True)

